export default [
  {
    ignores: ['dist/**'],
    files: ['**/*.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        console: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        Blob: 'readonly',
        URL: 'readonly',
        XLSX: 'readonly',
        jsPDF: 'readonly',
        __dirname: 'readonly',
        fetch: 'readonly',
        MutationObserver: 'readonly',
        getComputedStyle: 'readonly',
        Notification: 'readonly',
        CustomEvent: 'readonly',
        btoa: 'readonly',
        atob: 'readonly',
        self: 'readonly',
        global: 'readonly',
        IDBDatabase: 'readonly',
        IDBObjectStore: 'readonly',
        IDBIndex: 'readonly',
        IDBCursor: 'readonly',
        IDBTransaction: 'readonly',
        indexedDB: 'readonly',
        DOMException: 'readonly',
        Headers: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        TextDecoder: 'readonly',
        TextEncoder: 'readonly',
        Image: 'readonly',
        AbortController: 'readonly',
        clients: 'readonly',
        location: 'readonly',
        chrome: 'readonly',
        browser: 'readonly',
        gapi: 'readonly',
        MessageChannel: 'readonly',
        Buffer: 'readonly',
        router: 'readonly',
        modal: 'readonly',
        caches: 'readonly',
      }
    },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': 'warn',
      'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'warn',
      'semi': ['error', 'always'],
      'quotes': ['error', 'single'],
      'indent': ['error', 2],
      'no-trailing-spaces': 'error',
      'eol-last': 'error',
      'curly': 'error',
      'eqeqeq': 'error',
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-new-func': 'error',
      'no-script-url': 'error'
    }
  }
]; 